name: Web App Build Push
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME:  billymumby/addemowebapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: docker build -f ./src/WebApp/Dockerfile -t $DOCKER_IMAGE_NAME:${{ github.event.inputs.image_tag }} .

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_IMAGE_NAME:${{ github.event.inputs.image_tag }}
